### ISSUE TITLE
descarga del Archivo "Características" del BCV

### ISSUE THREAD

**Issue by danrisk** [synergyvision/Riesgo-de-Mercado#2]
Al descargar el archivo características, sale una pantalla en blanco que dice "not found", sin embargo el archivo en cuestión si se actualiza normalmente, hay que revisar el archivo de extracción  y verificar que en "content" tenga una dirección relativa con el fin que el archivo se descargue Alí sin imprimir en pantalla.

**Comment by Fr3ddy1** [comment]
problema solucionado
