### ISSUE TITLE
Estilo y prestaciones en los gráficos

### ISSUE THREAD

**Issue by danrisk** [synergyvision/Riesgo-de-Mercado#6]
El estilo y  el patrón de colores debería ser congruente con los colores de la plantilla y por ende de la empresa, además los mismo deberían tener etiquetas interactivas que le permitan al usuario observar los valores en cada segmento de curva así como en cualquier área del gráfico.

**Comment by Fr3ddy1** [comment]
Listas las etiquetas interactivas en todos los gráficos
