### ISSUE TITLE
Formato en la elección de parámetro

### ISSUE THREAD

**Issue by danrisk** [synergyvision/Riesgo-de-Mercado#7]
- [x] En cada metodología existe la posibilidad de elegir parámetros de manera manualsegún la experiencia del usuario, las cantidades deben incluir al menos 2 posiciones decimales.

- [x] Se debe controlar la reactividad en esta parte de la aplicación, preferiblemente con un ActionButton y la función ObserveEvent.

**Comment by Fr3ddy1** [comment]
Parámetros y reactividad solventada
